project:
  type: website

website:
  title: "Data Visualization"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Assignment 1
        href: assignment1.qmd
    right:
      - icon: github
        href: https://github.com/AntonSutiagin

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


